fix some Docker build issues
(1) Build complains about captial letters in stage names:

    > ERROR: failed to solve: failed to parse stage name "CVC5-base": invalid reference
    > format: repository name must be lowercase

(2) Ginac 1.8.6 download link is dead, since 1.8.7 was released.
    If they don't keep those links alive, maybe in the long term it's better to
    install Ginac via their git repo.

(3) The second `xbps-install` throws:

    >  1.511 The 'xbps' package must be updated, please run `xbps-install -u xbps`
    >
    >   ------
    >   Dockerfile:5
    >   --------------------
    >      3 |
    >      4 |     RUN xbps-install -yS xbps
    >      5 | >>> RUN xbps-install -ySu

    The suggested fix does not work for me. Replacing lines 4,5 with just

    > RUN xbps-install -ySu xbps

    works for some reason.

(4) In the `purrs` bulid stage we install the package `giac-devel` which seems to
    have conflicting dependencies with already installed packages. As a workaround,
    simply updating the offending packages explicitly seems to work.